fieldLayouts:
  dc3edf93-e837-4b7a-b1dc-3f5d525c4f09:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: blog
name: Blog
siteSettings:
  f2ce3f0f-3d51-4f3c-bebc-38c39c95c6b9:
    hasUrls: true
    template: blog/_category
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 423a73d2-0917-4bd4-a431-c21b264ec17e
