fieldLayouts:
  206c9bbf-0fba-4d44-b9c6-da670992b046:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: images
hasUrls: true
name: Images
settings:
  path: '@webroot/uploads'
sortOrder: 1
type: craft\volumes\Local
url: '@web/uploads'
