dateModified: 1604523261
email:
  fromEmail: josef.renner@gmail.com
  fromName: 'craft test'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  ckeditor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
system:
  edition: solo
  live: true
  name: 'Josef Renner'
  schemaVersion: 3.5.13
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
